global: 
  pattern: xeonllm

  clusterDomain: lab.com

  xeonllm:
    namespace: xeon-llm
    servingRuntime:
      namespace: rag-demo
      name: tgi-70b-1
    build_envs: [] # http_proxy/https_prxy can be set here
    runtime_envs: []
    
    llm_server_for_xeon:  
      image: image-registry.openshift-image-registry.svc:5000/xeon-llm/llm-tgi:latest
      git_ref: main # make sure to validate buildconfig & other change scope before updating
      #git_ref: 8ebe2bf # make sure to validate buildconfig & other change scope before updating
