apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker_compose.yaml
    kompose.version: 1.33.0 (3ce457399)
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "5"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"chatqna:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"chatqna-xeon-backend-server\")].image"}]'
  labels:
    io.kompose.service: chatqna-xeon-backend-server
  name: chatqna-xeon-backend-server
  namespace: {{ .Values.global.xeonllm.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: chatqna-xeon-backend-server
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker_compose.yaml
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/xeon-default: "true"
        io.kompose.service: chatqna-xeon-backend-server
    spec:
      containers:
        - env:
            - name: MEGA_SERVICE_HOST_IP
              value: megaservice-{{ .Values.global.xeonllm.namespace }}.apps.{{ .Values.global.clusterDomain }}
            {{- if .Values.global.xeonllm.runtime_envs }}
            {{- range .Values.global.xeonllm.runtime_envs }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
            {{- end }}           
            {{- if .Values.global.xeonllm.chatqna_xeon_backend.megaservice_envs }}
            {{- range .Values.global.xeonllm.chatqna_xeon_backend.megaservice_envs }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
            {{- end }}           
          image: {{ .Values.global.xeonllm.chatqna_xeon_backend.image }}
          name: chatqna-xeon-backend-server
          ports:
            - containerPort: 8888
              protocol: TCP
          volumeMounts:
            - mountPath: /home/user/megaservice-config.yaml
              name: megaservice-config
              subPath: megaservice-config.yaml
      restartPolicy: Always
      volumes:
        - name: megaservice-config 
          configMap:
            name: megaservice-config
            defaultMode: 0755
