kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: chatqna-megaservice-server
  namespace: {{ .Values.global.xeonllm.namespace }}
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  output:
    to:
      kind: "ImageStreamTag"
      name: "chatqna:latest"
  failedBuildsHistoryLimit: 5
  successfulBuildsHistoryLimit: 5
  nodeSelector: null
  postCommit: {}
  resources: {}
  runPolicy: SerialLatestOnly
  source:
    contextDir: ChatQnA/docker
    git:
      ref: {{ .Values.global.xeonllm.chatqna_xeon_backend.git_ref }}
      uri: https://github.com/opea-project/GenAIExamples.git
    type: Git
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
      {{- if .Values.global.xeonllm.build_envs }}
      env:
      {{- range .Values.global.xeonllm.build_envs }}
      - name: {{ .name }}
        value: {{ .value }}
      {{- end }}
      {{- end }}
  triggers:
  - type: ConfigChange
