kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: llm-tgi-xeon-server
  namespace: {{ .Values.global.xeonllm.namespace }}
spec:
  output:
    to:
      kind: "ImageStreamTag"
      name: "llm-tgi:latest"
  failedBuildsHistoryLimit: 5
  successfulBuildsHistoryLimit: 5
  nodeSelector: null
  postCommit: {}
  resources: {}
  runPolicy: SerialLatestOnly
  source:
    git:
      ref: {{ .Values.global.xeonllm.llm_server_for_xeon.git_ref }}
      uri: https://github.com/opea-project/GenAIComps.git
    type: Git
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: comps/llms/text-generation/tgi/Dockerfile
      {{- if .Values.global.xeonllm.build_envs }}
      env:
      {{- range .Values.global.xeonllm.build_envs }}
      - name: {{ .name }}
        value: {{ .value }}
      {{- end }}
      {{- end }}
  triggers:
  - type: ConfigChange
